### ISSUE TITLE
Падает приложение

### ISSUE THREAD

**Issue by AnikoV** [AnikoV/RatingVolsuWP8#10]
Приложение начало падать после последнего коммита "Добавила все предметы, поправила статистику". После перехода на экран рейтинга Группы

**Comment by juyka** [comment]
Не воспроизводится. Какую группу выбираешь?

**Comment by AnikoV** [comment]
Да, у меня тоже не воспроизводится, раньше любую группу когда выбирал то падало, щас норм)

**Comment by AnikoV** [comment]
Снова воспроизвёлся баг. С нуля запустил приложение выбрал рейтинг группы ввёл нашу группу. После небольшого ожидания ответа от сервера приложение упало. Благо был в отладке - есть инфа.

{System.NullReferenceException: Object reference not set to an instance of an object.
   at RatingVolsuAPI.DataBaseExtension.ToSubjectCollection(Dictionary`2 dictionary)
   at RatingVolsuAPI.RequestByGroup.GetRatingFromServer(Object RatingObject)
   at RatingVolsuAPI.RequestManager.<GetRatingOfGroup>d__30.MoveNext()}

Стектрейс:

   at RatingVolsuAPI.DataBaseExtension.ToSubjectCollection(Dictionary`2 dictionary)
   at RatingVolsuAPI.RequestByGroup.GetRatingFromServer(Object RatingObject)
   at RatingVolsuAPI.RequestManager.<GetRatingOfGroup>d__30.MoveNext()

возможно проблема в этом
![default](https://cloud.githubusercontent.com/assets/3219118/3814940/d078c2dc-1cbf-11e4-8a05-bc9fa2b6cb2c.PNG)

**Comment by juyka** [comment]
Вроде нашла проблему, теперь не должно падать
